using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OmniaWeb.ExtraTools
{
    public class Country
    {
        public Country()
        {
            countires = new List<string>();
         countires.Add("Afghanistan");
countires.Add("Albania");
countires.Add("Algeria");
countires.Add("Andorra");
countires.Add("Angola");
countires.Add("Antigua & Deps");
countires.Add("Argentina");
countires.Add("Armenia");
countires.Add("Australia");
countires.Add("Austria");
countires.Add("Azerbaijan");
countires.Add("Bahamas");
countires.Add("Bahrain");
countires.Add("Bangladesh");
countires.Add("Barbados");
countires.Add("Belarus");
countires.Add("Belgium");
countires.Add("Belize");
countires.Add("Benin");
countires.Add("Bhutan");
countires.Add("Bolivia");
countires.Add("Bosnia Herzegovina");
countires.Add("Botswana");
countires.Add("Brazil");
countires.Add("Brunei");
countires.Add("Bulgaria");
countires.Add("Burkina");
countires.Add("Burundi");
countires.Add("Cambodia");
countires.Add("Cameroon");
countires.Add("Canada");
countires.Add("Cape Verde");
countires.Add("Central African Rep");
countires.Add("Chad");
countires.Add("Chile");
countires.Add("China");
countires.Add("Colombia");
countires.Add("Comoros");
countires.Add("Congo");
countires.Add("Congo {Democratic Rep}");
countires.Add("Costa Rica");
countires.Add("Croatia");
countires.Add("Cuba");
countires.Add("Cyprus");
countires.Add("Czech Republic");
countires.Add("Denmark");
countires.Add("Djibouti");
countires.Add("Dominica");
countires.Add("Dominican Republic");
countires.Add("East Timor");
countires.Add("Ecuador");
countires.Add("Egypt");
countires.Add("El Salvador");
countires.Add("Equatorial Guinea");
countires.Add("Eritrea");
countires.Add("Estonia");
countires.Add("Ethiopia");
countires.Add("Fiji");
countires.Add("Finland");
countires.Add("France");
countires.Add("Gabon");
countires.Add("Gambia");
countires.Add("Georgia");
countires.Add("Germany");
countires.Add("Ghana");
countires.Add("Greece");
countires.Add("Grenada");
countires.Add("Guatemala");
countires.Add("Guinea");
countires.Add("Guinea-Bissau");
countires.Add("Guyana");
countires.Add("Haiti");
countires.Add("Honduras");
countires.Add("Hungary");
countires.Add("Iceland");
countires.Add("India");
countires.Add("Indonesia");
countires.Add("Iran");
countires.Add("Iraq");
countires.Add("Ireland {Republic}");
countires.Add("Israel");
countires.Add("Italy");
countires.Add("Ivory Coast");
countires.Add("Jamaica");
countires.Add("Japan");
countires.Add("Jordan");
countires.Add("Kazakhstan");
countires.Add("Kenya");
countires.Add("Kiribati");
countires.Add("Korea North");
countires.Add("Korea South");
countires.Add("Kosovo");
countires.Add("Kuwait");
countires.Add("Kyrgyzstan");
countires.Add("Laos");
countires.Add("Latvia");
countires.Add("Lebanon");
countires.Add("Lesotho");
countires.Add("Liberia");
countires.Add("Libya");
countires.Add("Liechtenstein");
countires.Add("Lithuania");
countires.Add("Luxembourg");
countires.Add("Macedonia");
countires.Add("Madagascar");
countires.Add("Malawi");
countires.Add("Malaysia");
countires.Add("Maldives");
countires.Add("Mali");
countires.Add("Malta");
countires.Add("Marshall Islands");
countires.Add("Mauritania");
countires.Add("Mauritius");
countires.Add("Mexico");
countires.Add("Micronesia");
countires.Add("Moldova");
countires.Add("Monaco");
countires.Add("Mongolia");
countires.Add("Montenegro");
countires.Add("Morocco");
countires.Add("Mozambique");
countires.Add("Myanmar, {Burma}");
countires.Add("Namibia");
countires.Add("Nauru");
countires.Add("Nepal");
countires.Add("Netherlands");
countires.Add("New Zealand");
countires.Add("Nicaragua");
countires.Add("Niger");
countires.Add("Nigeria");
countires.Add("Norway");
countires.Add("Oman");
countires.Add("Pakistan");
countires.Add("Palau");
countires.Add("Panama");
countires.Add("Papua New Guinea");
countires.Add("Paraguay");
countires.Add("Peru");
countires.Add("Philippines");
countires.Add("Poland");
countires.Add("Portugal");
countires.Add("Qatar");
countires.Add("Romania");
countires.Add("Russian Federation");
countires.Add("Rwanda");
countires.Add("St Kitts & Nevis");
countires.Add("St Lucia");
countires.Add("Saint Vincent & the Grenadines");
countires.Add("Samoa");
countires.Add("San Marino");
countires.Add("Sao Tome & Principe");
countires.Add("Saudi Arabia");
countires.Add("Senegal");
countires.Add("Serbia");
countires.Add("Seychelles");
countires.Add("Sierra Leone");
countires.Add("Singapore");
countires.Add("Slovakia");
countires.Add("Slovenia");
countires.Add("Solomon Islands");
countires.Add("Somalia");
countires.Add("South Africa");
countires.Add("South Sudan");
countires.Add("Spain");
countires.Add("Sri Lanka");
countires.Add("Sudan");
countires.Add("Suriname");
countires.Add("Swaziland");
countires.Add("Sweden");
countires.Add("Switzerland");
countires.Add("Syria");
countires.Add("Taiwan");
countires.Add("Tajikistan");
countires.Add("Tanzania");
countires.Add("Thailand");
countires.Add("Togo");
countires.Add("Tonga");
countires.Add("Trinidad & Tobago");
countires.Add("Tunisia");
countires.Add("Turkey");
countires.Add("Turkmenistan");
countires.Add("Tuvalu");
countires.Add("Uganda");
countires.Add("Ukraine");
countires.Add("United Arab Emirates");
countires.Add("United Kingdom");
countires.Add("United States");
countires.Add("Uruguay");
countires.Add("Uzbekistan");
countires.Add("Vanuatu");
countires.Add("Vatican City");
countires.Add("Venezuela");
countires.Add("Vietnam");
countires.Add("Yemen");
countires.Add("Zambia");
countires.Add("Zimbabwe");

        }
        public List<string> countires { get; set; }
            

    }
}