// <auto-generated />
namespace TestGUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingprojectrefid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingprojectrefid));
        
        string IMigrationMetadata.Id
        {
            get { return "201706160402142_adding project ref id "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
